<a href="https://colab.research.google.com/github/mlingley/portfolio/blob/main/Transpose_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r'C:\Users\malin\Downloads\metacritic_games.csv')
df

,Unnamed: 0.1,Unnamed: 0,0,1,2,3,4,5,6,7,...,12120,12121,12122,12123,12124,12125,12126,12127,12128,12129
0,0,Title,Last Train Home,Call of Duty: Modern Warfare III,Super Mario RPG,Alan Wake II,SteamWorld Build,Persona 5 Tactica,Like a Dragon Gaiden: The Man Who Erased His Name,Marvel's Spider-Man 2,...,Tom Clancy's Rainbow Six 3,Conspiracies,The Evil Within: The Consequence,The Next Penelope,Guilty Gear XX Accent Core,Operencia: The Stolen Sun,Empire Earth III,Frozen Synapse Prime,Pirates of the Caribbean: Dead Man's Chest,Caveman Warriors
1,1,Release_date,"Nov 28, 2023","Nov 10, 2023","Nov 17, 2023","Oct 27, 2023","Dec 1, 2023","Nov 17, 2023","Nov 9, 2023","Oct 20, 2023",...,"Nov 12, 2003","Nov 10, 2003","Apr 21, 2015","Dec 21, 2017","Oct 15, 2007","Mar 29, 2019","Nov 6, 2007","Sep 23, 2014","Jun 27, 2006","Dec 5, 2017"
2,2,Metascore,83,56,84,88,73,75,78,90,...,86,53,75,79,75,82,50,84,52,52
3,3,User_score,7.3,1.9,8.1,8.9,tbd,7.8,8.1,9.1,...,7.7,tbd,9.1,7.2,8.3,7.1,3.3,6.8,7.5,5.6

In [ ]:
df_transposed = df.T
df_transposed

,0,1,2,3
Unnamed: 0.1,0,1,2,3
Unnamed: 0,Title,Release_date,Metascore,User_score
0,Last Train Home,"Nov 28, 2023",83,7.3
1,Call of Duty: Modern Warfare III,"Nov 10, 2023",56,1.9
2,Super Mario RPG,"Nov 17, 2023",84,8.1
...,...,...,...,...
12125,Operencia: The Stolen Sun,"Mar 29, 2019",82,7.1
12126,Empire Earth III,"Nov 6, 2007",50,3.3
12127,Frozen Synapse Prime,"Sep 23, 2014",84,6.8
12128,Pirates of the Caribbean: Dead Man's Chest,"Jun 27, 2006",52,7.5
12129,Caveman Warriors,"Dec 5, 2017",52,5.6

In [ ]:
df_transposed.to_csv(r"C:\Users\malin\Downloads\metacritic_games1.csv", index=False)